int		g_row;
int		g_col;
int		g_size;
int		validate_map(char *map_data);
int		get_col(char *map_data);
int		get_row(char *map_data);
int		read_map(int map_filedes, char **data);
char	**write_map_arr(char **map_array, char *map_data);
int		allocate_map_arr(char ***map_array, char *map_data);
int		open_map(const char *map_filename);
void	ft_putstr(char *str);
void	ft_putchar(char c);
char	*ft_strncpy(char *dest, char *src, unsigned int n);
